/**
 * Schema conventions used by every migration:
 * - foreign keys are enabled for every connection;
 * - identifiers use snake_case and explicit constraints;
 * - timestamps are UTC ISO-8601 text generated by repositories;
 * - natural uniqueness is expressed with UNIQUE or PRIMARY KEY constraints.
 */
export const MIGRATION_TABLE = "schema_migrations" as const;

export const CREATE_MIGRATION_TABLE_SQL = `
  CREATE TABLE IF NOT EXISTS ${MIGRATION_TABLE} (
    version INTEGER PRIMARY KEY CHECK (version > 0),
    name TEXT NOT NULL UNIQUE CHECK (length(name) > 0),
    applied_at TEXT NOT NULL
  ) STRICT
`;
